### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by peterwoodworth** [sachinh35/insomnia-plugin-aws-profile-creds#3]
Hi! We're interested in using this software, but would like to know what rights we have when it comes to using it. Would you be able to license this project? Thank you

**Comment by sachinh35** [comment]
Hey,

Thanks for reaching out. I'm a little busy this week. Will update the repo
with the correct license over the weekend. Feel free to use it in the
meantime.

Best,
Sachin

**Comment by peterwoodworth** [comment]
Hi, any update here @sachinh35? We won't feel comfortable proceeding to use the software without knowing which license you intend to apply

**Comment by sachinh35** [comment]
Added `LICENSE.txt`. Closing the issue.

**Comment by peterwoodworth** [comment]
Thank you!
